config/routes.rb
Recettear::Application.routes.draw do
  devise_for :users
  resources :sales_cycles

  resources :orders

  resources :order_categories

  resources :inventory_items

  resources :item_categories

  resources :items

  root 'app#app'

end

app/models/item_category.rb
class ItemCategory < ActiveRecord::Base

	validates :name, presence: true

	has_many :items
	has_and_belongs_to_many :order_categories
end

app/controllers/item_categories_controller.rb
class ItemCategoriesController < ApplicationController
  before_action :set_item_category, only: [:show, :edit, :update, :destroy]

  # GET /item_categories
  # GET /item_categories.json
  def index
    @item_categories = ItemCategory.all
  end

  # GET /item_categories/1
  # GET /item_categories/1.json
  def show
  end

  # GET /item_categories/new
  def new
    @item_category = ItemCategory.new
  end

  # GET /item_categories/1/edit
  def edit
  end

  # POST /item_categories
  # POST /item_categories.json
  def create
    @item_category = ItemCategory.new(item_category_params)

    respond_to do |format|
      if @item_category.save
        format.html { redirect_to @item_category, notice: 'Item category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item_category }
      else
        format.html { render action: 'new' }
        format.json { render json: @item_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_categories/1
  # PATCH/PUT /item_categories/1.json
  def update
    respond_to do |format|
      if @item_category.update(item_category_params)
        format.html { redirect_to @item_category, notice: 'Item category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_categories/1
  # DELETE /item_categories/1.json
  def destroy
    @item_category.destroy
    respond_to do |format|
      format.html { redirect_to item_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_category
      @item_category = ItemCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_category_params
      params.require(:item_category).permit(:name)
    end
end

app/helpers/item_categories_helper.rb
module ItemCategoriesHelper
end

app/views/item_categories/_form.html.erb
<%= form_for(@item_category) do |f| %>
  <% if @item_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_category.errors.count, "error") %> prohibited this item_category from being saved:</h2>

      <ul>
      <% @item_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_categories/edit.html.erb
<h1>Editing item_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_category %> |
<%= link_to 'Back', item_categories_path %>

app/views/item_categories/index.html.erb
<h1>Listing item_categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @item_categories.each do |item_category| %>
      <tr>
        <td><%= item_category.name %></td>
        <td><%= link_to 'Show', item_category %></td>
        <td><%= link_to 'Edit', edit_item_category_path(item_category) %></td>
        <td><%= link_to 'Destroy', item_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item category', new_item_category_path %>

app/views/item_categories/new.html.erb
<h1>New item_category</h1>

<%= render 'form' %>

<%= link_to 'Back', item_categories_path %>

app/views/item_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item_category.name %>
</p>

<%= link_to 'Edit', edit_item_category_path(@item_category) %> |
<%= link_to 'Back', item_categories_path %>