config/routes.rb
Recettear::Application.routes.draw do
  devise_for :users
  resources :sales_cycles

  resources :orders

  resources :order_categories

  resources :inventory_items

  resources :item_categories

  resources :items

  root 'app#app'

end

app/models/sales_cycle.rb
class SalesCycle < ActiveRecord::Base

	validates :user, presence: true

	belongs_to :user
	has_many :inventory_items
	has_many :items, :through => :inventory_items
	has_many :orders
end

app/controllers/sales_cycles_controller.rb
class SalesCyclesController < ApplicationController
  before_action :set_sales_cycle, only: [:show, :edit, :update, :destroy]

  # GET /sales_cycles
  # GET /sales_cycles.json
  def index
    @sales_cycles = SalesCycle.all
  end

  # GET /sales_cycles/1
  # GET /sales_cycles/1.json
  def show
  end

  # GET /sales_cycles/new
  def new
    @sales_cycle = SalesCycle.new
  end

  # GET /sales_cycles/1/edit
  def edit
  end

  # POST /sales_cycles
  # POST /sales_cycles.json
  def create
    @sales_cycle = SalesCycle.new(sales_cycle_params)

    respond_to do |format|
      if @sales_cycle.save
        format.html { redirect_to @sales_cycle, notice: 'Sales cycle was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sales_cycle }
      else
        format.html { render action: 'new' }
        format.json { render json: @sales_cycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales_cycles/1
  # PATCH/PUT /sales_cycles/1.json
  def update
    respond_to do |format|
      if @sales_cycle.update(sales_cycle_params)
        format.html { redirect_to @sales_cycle, notice: 'Sales cycle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sales_cycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales_cycles/1
  # DELETE /sales_cycles/1.json
  def destroy
    @sales_cycle.destroy
    respond_to do |format|
      format.html { redirect_to sales_cycles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sales_cycle
      @sales_cycle = SalesCycle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sales_cycle_params
      params.require(:sales_cycle).permit(:customerCount, :user_id)
    end
end

app/helpers/sales_cycles_helper.rb
module SalesCyclesHelper
end

app/views/sales_cycles/_form.html.erb
<%= form_for(@sales_cycle) do |f| %>
  <% if @sales_cycle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sales_cycle.errors.count, "error") %> prohibited this sales_cycle from being saved:</h2>

      <ul>
      <% @sales_cycle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customerCount %><br>
    <%= f.number_field :customerCount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales_cycles/edit.html.erb
<h1>Editing sales_cycle</h1>

<%= render 'form' %>

<%= link_to 'Show', @sales_cycle %> |
<%= link_to 'Back', sales_cycles_path %>

app/views/sales_cycles/index.html.erb
<h1>Listing sales_cycles</h1>

<table>
  <thead>
    <tr>
      <th>Customercount</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sales_cycles.each do |sales_cycle| %>
      <tr>
        <td><%= sales_cycle.customerCount %></td>
        <td><%= link_to 'Show', sales_cycle %></td>
        <td><%= link_to 'Edit', edit_sales_cycle_path(sales_cycle) %></td>
        <td><%= link_to 'Destroy', sales_cycle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sales cycle', new_sales_cycle_path %>

app/views/sales_cycles/new.html.erb
<h1>New sales_cycle</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_cycles_path %>

app/views/sales_cycles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customercount:</strong>
  <%= @sales_cycle.customerCount %>
</p>

<%= link_to 'Edit', edit_sales_cycle_path(@sales_cycle) %> |
<%= link_to 'Back', sales_cycles_path %>