config/routes.rb
Recettear::Application.routes.draw do
  devise_for :users
  resources :sales_cycles

  resources :orders

  resources :order_categories

  resources :inventory_items

  resources :item_categories

  resources :items

  root 'app#app'

end

app/models/inventory_item.rb
class InventoryItem < ActiveRecord::Base

	validates :item, presence: true
	validates :sales_cycle, presence: true
	validates :location, presence: true

	belongs_to :sales_cycle
	belongs_to :item
end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController
  before_action :set_inventory_item, only: [:show, :edit, :update, :destroy]

  # GET /inventory_items
  # GET /inventory_items.json
  def index
    @inventory_items = InventoryItem.all
  end

  # GET /inventory_items/1
  # GET /inventory_items/1.json
  def show
  end

  # GET /inventory_items/new
  def new
    @inventory_item = InventoryItem.new
  end

  # GET /inventory_items/1/edit
  def edit
  end

  # POST /inventory_items
  # POST /inventory_items.json
  def create
    @inventory_item = InventoryItem.new(inventory_item_params)

    respond_to do |format|
      if @inventory_item.save
        format.html { redirect_to @inventory_item, notice: 'Inventory item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @inventory_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @inventory_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventory_items/1
  # PATCH/PUT /inventory_items/1.json
  def update
    respond_to do |format|
      if @inventory_item.update(inventory_item_params)
        format.html { redirect_to @inventory_item, notice: 'Inventory item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @inventory_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_items/1
  # DELETE /inventory_items/1.json
  def destroy
    @inventory_item.destroy
    respond_to do |format|
      format.html { redirect_to inventory_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory_item
      @inventory_item = InventoryItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_item_params
      params.require(:inventory_item).permit(:sold, :price, :item_id, :sales_cycle_id, :location)
    end
end

app/helpers/inventory_items_helper.rb
module InventoryItemsHelper
end

app/views/inventory_items/_form.html.erb
<%= form_for(@inventory_item) do |f| %>
  <% if @inventory_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory_item.errors.count, "error") %> prohibited this inventory_item from being saved:</h2>

      <ul>
      <% @inventory_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sold %><br>
    <%= f.check_box :sold %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventory_items/edit.html.erb
<h1>Editing inventory_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory_item %> |
<%= link_to 'Back', inventory_items_path %>

app/views/inventory_items/index.html.erb
<h1>Listing inventory_items</h1>

<table>
  <thead>
    <tr>
      <th>Sold</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @inventory_items.each do |inventory_item| %>
      <tr>
        <td><%= inventory_item.sold %></td>
        <td><%= inventory_item.price %></td>
        <td><%= link_to 'Show', inventory_item %></td>
        <td><%= link_to 'Edit', edit_inventory_item_path(inventory_item) %></td>
        <td><%= link_to 'Destroy', inventory_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inventory item', new_inventory_item_path %>

app/views/inventory_items/new.html.erb
<h1>New inventory_item</h1>

<%= render 'form' %>

<%= link_to 'Back', inventory_items_path %>

app/views/inventory_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sold:</strong>
  <%= @inventory_item.sold %>
</p>

<p>
  <strong>Price:</strong>
  <%= @inventory_item.price %>
</p>

<%= link_to 'Edit', edit_inventory_item_path(@inventory_item) %> |
<%= link_to 'Back', inventory_items_path %>